USE [master]
GO
CREATE LOGIN [PF] WITH PASSWORD=N'PF', DEFAULT_DATABASE=[Proyecto final], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

USE [Proyecto final]
GO
CREATE USER [PF] FOR LOGIN [PF]
GO
USE [Proyecto final]
GO
ALTER ROLE [db_owner] ADD MEMBER [PF]
GO
